// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO4QcTrs4Xh-x3qEci9-7ZO1jqyzfC1P8',
    appId: '1:365573019569:web:f90d97dde3e7af3aa6cf90',
    messagingSenderId: '365573019569',
    projectId: 'movies-app-5f3eb',
    authDomain: 'movies-app-5f3eb.firebaseapp.com',
    storageBucket: 'movies-app-5f3eb.firebasestorage.app',
    measurementId: 'G-VDG3776RVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3tUpetT23MfavWLm4rbIWBwA4xBODtmY',
    appId: '1:365573019569:android:1c6fa1813e5e0b2ca6cf90',
    messagingSenderId: '365573019569',
    projectId: 'movies-app-5f3eb',
    storageBucket: 'movies-app-5f3eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA8RbsVUFFYCQCLzwJYEQ4nOBLH35LKXI',
    appId: '1:365573019569:ios:008bdfacd3b32994a6cf90',
    messagingSenderId: '365573019569',
    projectId: 'movies-app-5f3eb',
    storageBucket: 'movies-app-5f3eb.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );
}
